<?php
//
// GGDD Framework View File
//
// Filename     : index.tpl
// Generated on : 2012-11-07 15:42:20
// Version file : 1.0
//
// Generated by GGDD Infinity Software
// For more information, thank you for
// visiting: http://www.ggddcomputing.com
//
?>
<!-- View contents -->
