<?php
//
// GGDD Framework Preprocess File
//
// Filename     : preprocess_default.php
// Generated on : 2012-11-07 15:42:20
// Version file : 1.0
//
// Generated by GGDD Infinity Software
// For more information, thank you for
// visiting: http://www.ggddcomputing.com

// This file will be exectuted just before
// the header template. You can configure,
// by exemple, title or description page, etc.

define("APP_TITLE",        "Urbajob");
define("APP_STYLE",        "./App/Assets/Styles/style.css");
define("APP_STYLE_GRID",   "./App/Assets/Styles/grid.css");
define("APP_STYLE_ENGINE",   "./App/Assets/Styles/validationEngine.jquery.css");
define("APP_FANCY",   	   "./App/Assets/Js/fancydropdown.js");
define("APP_KEYWORDS",     "");
define("APP_DESCRIPTION",  "");